from typing import Dict, List, Any

class DoctorSummaryGenerator:
    """
    Generates a dense, clinical-format summary of a patient's medical report
    designed specifically for physician review (M.D. format).
    """

    @staticmethod
    def generate_summary(
        patient_profile: Dict[str, Any],
        parameters: List[Dict[str, Any]],
        predictions: Dict[str, float],
        health_score: Dict[str, Any],
        recommendations: List[Dict[str, Any]]
    ) -> str:
        lines = []

        # Header
        name = patient_profile.get("full_name", "Unknown Patient")
        age = patient_profile.get("age", "U")
        gender = str(patient_profile.get("gender", "U"))[0].upper()
        lines.append(f"PATIENT CLINICAL SUMMARY — {name.upper()}")
        lines.append(f"Demographics: {age}yo {gender}")

        bmi = patient_profile.get('bmi')
        if bmi:
            lines.append(f"BMI: {float(bmi):.1f}")

        lines.append("-" * 50)

        # High Priority Flags (Abnormal Parameters)
        abnormals = [p for p in parameters if p.get('flag', 'NORMAL').upper() != 'NORMAL']
        if abnormals:
            lines.append("## CLINICAL FINDINGS (OUT OF BOUNDS):")
            for p in abnormals:
                name_p = p.get('canonical_name') or p.get('parameter_name', 'Unknown')
                val = p.get('measured_value', 'N/A')
                unit = p.get('unit', '')
                flag = p.get('flag', 'ABNORMAL').upper()
                lines.append(f"• {name_p}: {val} {unit} [{flag}]")
        else:
            lines.append("## CLINICAL FINDINGS: All measured laboratory parameters are within normal reference ranges.")
        lines.append("")

        # Predictive Risk Factors
        lines.append("## ALGORITHMIC RISK ASSESSMENT:")
        high_risks = [k for k, v in predictions.items() if v > 0.5]
        med_risks = [k for k, v in predictions.items() if 0.3 <= v <= 0.5]

        if high_risks:
            lines.append(f"• ELEVATED RISK (>50%): {', '.join(high_risks)}")
        if med_risks:
            lines.append(f"• MODERATE RISK (30-50%): {', '.join(med_risks)}")
        if not high_risks and not med_risks:
            lines.append("• No prominent disease risks identified above baseline threshold.")

        score = health_score.get('overall_score', 'N/A')
        lines.append(f"• Composite Health Index: {score}/100")
        lines.append("")

        # Suggested Interventions
        lines.append("## SUGGESTED INTERVENTIONS (AI-GENERATED):")
        if recommendations:
            for i, rec in enumerate(recommendations[:3], 1):
                title = rec.get("title", "Recommendation")
                target = rec.get("target_condition", "")
                tgt_str = f" (Target: {target})" if target else ""
                lines.append(f"{i}. {title}{tgt_str}")
        else:
            lines.append("No specific interventions generated at this time.")

        lines.append("-" * 50)
        lines.append("Generated by MedInsight AI. Validated by _________ (MD).")

        return "\n".join(lines)
